RusticaWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/urls.py
from django.urls import path
from .views import home,products,perfil,exit,register,about,agregar_producto,restar_producto,eliminar_producto,limpiar_carrito
from .views import crear,listado,editar,eliminar
from . import views





from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', home, name='home'),
    path('products/', products, name='products'),
    path('perfil/', perfil, name='perfil'),
    path('logout/', exit , name='exit'),
    path('register/', register , name='register'),
    path('about/', about , name='about'),
    path('agregar/<int:producto_id>/', agregar_producto, name="Add"),
 #   path('eliminar/<int:producto_id>/', eliminar_producto, name="Del"),
    path('restar/<int:producto_id>/', restar_producto, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),

    path('cerveza/crear', crear, name='crear'),
    path('listado/', listado, name='listado'),
    path('cerveza/editar/', editar, name='editar'),
    path('cerveza/editar/<int:id>/', editar, name='editar_id'),
    path('eliminar/<int:id>/', eliminar, name='eliminar'),
    path('reviews/<int:producto_id>/', views.lista_reviews, name='lista_reviews'),
    path('reviews/<int:review_id>/eliminar/', views.eliminar_review, name='eliminar_review'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


class Producto(models.Model):
    nombre = models.CharField(max_length=64)
    descripcion = models.CharField(max_length=250, verbose_name="Descripcion")
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to='productos/', verbose_name="imagen", null=True)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return f'{self.nombre} -> {self.precio}'   

    def delete(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    contenido = models.TextField()
    puntuacion = models.IntegerField()

    def __str__(self):
        return self.contenido




# Create your models here.
# xd

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Producto
from .models import Review

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email','password1', 'password2']
        
class CervezaForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['contenido', 'puntuacion']

core/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from .models import Producto
from core.Carrito import Carrito    
from .forms import CervezaForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseNotAllowed, JsonResponse
from .models import Review
from .forms import ReviewForm
# Create your views here.

def home(request):
    return render(request, 'index.html')


def products(request):
    productos = Producto.objects.all()
    return render(request, 'products.html', {'productos':productos})


@user_passes_test(lambda u: u.is_superuser)
def listado(request):
    productos = Producto.objects.all()
    print(listado)
    return render(request, 'cerveza/listado.html', {'productos':productos})


def agregar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.agregar(producto)
    return redirect("products")

def eliminar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.eliminar(producto)
    return redirect("products")

def restar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.restar(producto)
    return redirect("products")

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("products")
@login_required
def perfil(request):    
    return render(request, 'perfil.html')
def about(request):
    return render(request, 'about.html')
def exit(request):
    logout(request)
    return redirect('home')

def register(request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == 'POST':
        user_creation_form = CustomUserCreationForm(data=request.POST)
        if user_creation_form.is_valid():
            user_creation_form.save()

            user = authenticate(username=user_creation_form.cleaned_data['username'], password=user_creation_form.cleaned_data['password1'])
            login(request, user)
            return redirect('home')
    return render(request, 'registration/register.html',data)


@user_passes_test(lambda u: u.is_superuser)
def crear(request):
    if request.method == 'POST':
        formulario = CervezaForm(request.POST, request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect('listado')
    else:       
        formulario = CervezaForm()
    
    return render(request, 'cerveza/crear.html', {'formulario': formulario})

@user_passes_test(lambda u: u.is_superuser)
def editar(request, id=None):
    if id:
        producto = get_object_or_404(Producto, id=id)
    else:
        producto = None

    if request.method == 'POST':
        formulario = CervezaForm(request.POST, request.FILES, instance=producto)
        if formulario.is_valid():
            formulario.save()
            return redirect('listado')
    else:
        formulario = CervezaForm(instance=producto)

    return render(request, 'cerveza/editar.html', {'formulario': formulario})


@user_passes_test(lambda u: u.is_superuser)
def eliminar(request, id):
    producto = Producto.objects.get(id=id)
    producto.delete()
    return redirect("listado")

@login_required
def lista_reviews(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    reviews = Review.objects.filter(producto=producto)  # Filtrar las reviews por producto
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.producto = producto  # Asignar el producto a la review
            review.save()
            return redirect('lista_reviews', producto_id=producto_id)
    return render(request, 'lista_reviews.html', {'producto': producto, 'reviews': reviews, 'form': form})

@login_required
def eliminar_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if request.method == 'POST':
        review.delete()
        return redirect('lista_reviews', producto_id=review.producto_id)
    else:
        return HttpResponseNotAllowed(['POST'])

core/templates/about.html
{% load static %}
<!DOCTYPE html>
<html class="" lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <title>Rustica</title>
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'img/icono.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Delicious+Handrawn&display=swap" rel="stylesheet">
    
    <script src="{% static 'js/script.js' %}"></script>
    
    
    
</head>
  
<body class="fondo">

  {% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        
    <h1></h1>
    <div class="head">

        <div class="logo">
            <table>
                <tr>
                    <td><a href="#"><img src="{% static 'img/logo2.png' %}" height="100%" width="100%" alt="logonumero2"></a></td>
                    <td >
                        <p class="Nombrelogo">Rustica</p>
                    </td>
                </tr>
            </table>

        </div>


        <nav class="navbar">
          <a href="{% url 'home' %}">Inicio</a>
          <a href="{% url 'products' %}">Catalogo</a>
          <a class="bi bi-person-circle" href="{% url 'perfil' %}"></a>
          {% if request.user.is_authenticated %}
          <a href="{% url 'exit' %}"> Salir</a>
          {% else %}
          <a href="{% url 'login' %}"> Acceder</a>
          {% endif %}
      </nav>
    </div>

    <br>

    <br>
    <br>
    <br>
    <br>
    <br>
    <section id="Nosotros" class="content about">

      <h2 class="title">Nosotros</h2>
      <p>Nuestra Tienda:
          Somos una tienda en casa blanca dedicada exclusivamente a la venta de cervezas artesanales propias. Tenemos
          cerca de 6 cervezas distintas, de muy buena calidad
          por ahora solo contamos con 3 tipos de cervezas a la venta y otras 3 en produccion. Por el momento somos una
          tienda física, se hacen ventas presencialmente con el cliente cuando visita nuestro local y se hacen
          entregas en el plan del gran valparaiso,
          por ahora solo se reservan compras via whatsapp y por instagram.
          Queremos expandir nuestras ventas a más personas que aún no conocen nuestro local, llegar a hacer repartos
          tanto dentro de la ciudad como a otras ciudades,
          en todo Chile. Ubicados en km 3 Hacienda lo orozco,Casablanca como casa principal y tambien en el plan de
          valparaiso como lugar de entrega, Cervezeria Rustica.<br>
          <br>Nuestra Historia:
          Nuestro local fue fundado a fines de octubre de 2022. Los dueños somos Gonzalo y Andrea una pareja de dos
          Ingenieros Agrónomos que se conocieron estudiando Agronomía en Valdivia
          y donde también nació el amor por las cervezas.
          Hasta la actualidad ya hemos sido reconocidos por el público de Casa blanca y Valparaiso, teniendo muchos
          clientes que vuelven a ir todas las semanas, además fuimos beneficiarios de un fondo
          Crece de Sercotec y aparecimos en un reportaje del diario El mercurio.<br>
          <br>Nuestra Misión:
          Somos la única tienda en la V region dedicada exclusivamente a la venta de cervezas artesanales en botella y
          la única con la más alta calidad en la región.
          Nuestro objetivo es ofrecer la mejor cerveza que se adecué al gusto del cliente mediante una gran variedad y
          estilos junto a una orientación personalizada.
          Privilegiamos la calidad de la cerveza ante todo y así poder recomendarla tranquilamente,
          esto se respalda en base a recomendaciones de personas en el mismo rubro. Además se orienta al cliente en
          base a lo que busca desde la cerveza más ligera,
          hasta la cerveza más amarga o con más grados alcohólicos.<br>
      </p>
  </section>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    {% endblock %}
</body>

<footer>
  <div class="wooden-footer py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">Contacto</h4>
          <p><i class="bi bi-instagram"></i> cvza.rustica</p>
        </div>
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">Correo</h4>
          <p><i class="bi bi-envelope"></i> cvza.rustica@gmail.com</p>
        </div>
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">WhatsApp</h4>
          <p><i class="bi bi-whatsapp"></i> +569470283</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <button class="btn btn-orange" onclick="window.location.href='{% url 'about' %}'">Nosotros</button>
        </div>
      </div>
    </div>
  </div>
</footer>
</html>

core/templates/agregar.html
{% load static %}
<!DOCTYPE html>
<html class="" lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <title>Rustica</title>
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'img/icono.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Delicious+Handrawn&display=swap" rel="stylesheet">
    
    <script src="{% static 'js/script.js' %}"></script>
    
    
    
</head>
  
<body class="fondo">

  {% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        
    <h1></h1>
    <div class="head">

        <div class="logo">
            <table>
                <tr>
                    <td><a href="#"><img src="{% static 'img/logo2.png' %}" height="100%" width="100%" alt="logonumero2"></a></td>
                    <td >
                        <p class="Nombrelogo">Rustica</p>
                    </td>
                </tr>
            </table>

        </div>


        <nav class="navbar">
          <a href="{% url 'home' %}">Inicio</a>
          <a href="{% url 'products' %}">Catalogo</a>
          <a class="bi bi-person-circle" href="{% url 'perfil' %}"></a>
          {% if request.user.is_authenticated %}
          <a href="{% url 'exit' %}"> Salir</a>
          {% else %}
          <a href="{% url 'login' %}"> Acceder</a>
          {% endif %}
      </nav>
    </div>

    <br>

    <br>
    <br>
    <br>
    <br>
    <br>
    <p> owo
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    {% endblock %}
</body>

<footer>
  <div class="wooden-footer py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">Contacto</h4>
          <p><i class="bi bi-instagram"></i> cvza.rustica</p>
        </div>
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">Correo</h4>
          <p><i class="bi bi-envelope"></i> cvza.rustica@gmail.com</p>
        </div>
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">WhatsApp</h4>
          <p><i class="bi bi-whatsapp"></i> +569470283</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <button class="btn btn-orange" onclick="window.location.href='{% url 'about' %}'">Nosotros</button>
        </div>
      </div>
    </div>
  </div>
</footer>
</html>

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="" lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <title>Rustica</title>
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'img/icono.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Delicious+Handrawn&display=swap" rel="stylesheet">
    
    <script src="{% static 'js/script.js' %}"></script>
    
    
    
</head>
  
<body class="fondo">

  {% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        
    <h1></h1>
    <div class="head">

        <div class="logo">
            <table>
                <tr>
                    <td><a href="#"><img src="{% static 'img/logo2.png' %}" height="100%" width="100%" alt="logonumero2"></a></td>
                    <td >
                        <p class="Nombrelogo">Rustica</p>
                    </td>
                </tr>
            </table>

        </div>


        <nav class="navbar">
          <a href="{% url 'home' %}">Inicio</a>
          <a href="{% url 'products' %}">Catalogo</a>
          <a class="bi bi-person-circle" href="{% url 'perfil' %}"></a>
          {% if request.user.is_authenticated %}
          <a href="{% url 'exit' %}"> Salir</a>
          {% else %}
          <a href="{% url 'login' %}"> Acceder</a>
          {% endif %}
      </nav>
    </div>

    <br>

    <br>
    <br>
    <br>
    <br>
    <br>
    <p> owo
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    {% endblock %}
</body>

<footer>
  <div class="wooden-footer py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">Contacto</h4>
          <p><i class="bi bi-instagram"></i> cvza.rustica</p>
        </div>
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">Correo</h4>
          <p><i class="bi bi-envelope"></i> cvza.rustica@gmail.com</p>
        </div>
        <div class="col-md-4">
          <h4 class="text-center mb-4 wooden-title">WhatsApp</h4>
          <p><i class="bi bi-whatsapp"></i> +569470283</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <button class="btn btn-orange" onclick="window.location.href='{% url 'about' %}'">Nosotros</button>
        </div>
      </div>
    </div>
  </div>
</footer>
</html>

core/templates/carrito.html
  <table class="table table-striped card-color table-margin"> 
    <thead>
      <tr>
        <th scope="row" colspan="3" class="text-center">CARRITO</th>
      </tr>
      <tr>
        <th scope="col">NOMBRE</th>
        <th scope="col">Subtotal</th>
        <th scope="col">CANTIDAD</th>
      </tr>
    </thead>
    <tbody>
    {% if request.session.carrito.items %}
    {% for key, value in request.session.carrito.items %}
      <tr>
        <td>{{value.nombre}}</td>
        <td>${{value.acumulado}}</td>
        <td>{{value.cantidad}}  
          <a href="{% url 'Add' value.producto_id %}" class="badge btn btn-dark badge-dark">+</a>
          <a href="{% url 'Sub' value.producto_id %}" class="badge btn btn-dark badge-dark">-</a>
        </td>
      </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">
            <div class="alert alert-danger text-center"> Sin Productos </div>
        </td>
    </tr>
    {% endif %}
      <tr>
        <th scope="row">Total:</th>
        <td colspan="2">$ {{total_carrito}}</td>
      </tr>
    </tbody>
  </table>
  <hr>
  </div>
  <div class="row text-center">
      <div class="col-6"><a href="{% url 'CLS' %}" class="btn btn-danger">Limpiar</a></div>
      <div class="col-6"><a href="#" class="btn btn-success">Guardar</a></div>
  </div>

core/templates/cerveza/form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for campo in formulario %}
    <div class="mb-3">
        <label for ="" class="form-label">{{ campo.label }}</label>


        {% if campo.field.widget.input_type == 'file' and campo.value %}
        <br/>
        <img src="{{MEDIA_URL}}/productos/{{campo.value}}" height="400"/>
        
        {% endif %}

        <input type="{{campo.field.widget.input_type }}"
            class="form-control"
             name="{{ campo.name }}"
              id=""
               aria-describedby="helpId"
                placeholder="{{ campo.label }}"
                value="{{campo.value | default:''}}"
                >

    </div>
    <div class="col-12 help-text">  {{campo.errors}} </div> 
    {% endfor%}
    <input name="" id="" class="btn btn-success" onclick="confirmarAccion(event)" type="submit" value="Enviar Informacion">
    <a class="btn btn-orange" href="{% url 'listado' %}">Cancelar</a>
</form> 

core/templates/lista_reviews.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h2>Ultimas Reseñas</h2>
  <table class="table table-striped card-color table-margin mx-auto">
    <thead>
      <tr>
        <th>Usuario</th>
        <th>Comentario</th>
        <th>Puntuación</th>
        <th></th>
      </tr>
    </thead>
    <tbody> 
      {% for review in reviews %}
      <tr>
        <td>{{ review.user }}</td>
        <td>{{ review.contenido }}</td>
        <td>{{ review.puntuacion }}</td> 
        <td>{% if request.user.is_superuser %}
        <form method="POST" action="{% url 'eliminar_review' review.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger" onclick="confirmarAccion(event)">Eliminar</button>
        </form></td>
      {% endif %} 
      </tr>
      {% endfor %}
    </tbody>
  </table> 

  <div class="container">
    <h2>Crear nueva Reseña</h2>
    <form method="POST" action="{% url 'lista_reviews' producto_id=producto.id %}">
      {% csrf_token %}    
      <div class="form-group">
        <label for="id_contenido" class="text-color table-margin mx-auto">Comentario:</label>
        <textarea name="contenido" id="id_contenido" rows="3" required class="form-control text-orange"></textarea>
      </div>
      <div class="form-group">
        <label for="id_puntuacion" class="text-color mx-auto">Puntuación:</label>
        <div class="rating">
          <input type="hidden" name="puntuacion" id="id_puntuacion">
          <i class="star fas fa-star" data-value="1"></i>
          <i class="star fas fa-star" data-value="2"></i>
          <i class="star fas fa-star" data-value="3"></i>
          <i class="star fas fa-star" data-value="4"></i>
          <i class="star fas fa-star" data-value="5"></i>
        </div>
      </div>  
      <button type="submit" class="btn btn-primary" onclick="confirmarAccion(event)">Agregar Reseña</button>
    </form>
    <a href="{% url 'products' %}" class="btn btn-secondary mt-3">Volver a Productos</a>
  </div> 
  
  

  <!-- Cargar la biblioteca de Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <!-- Cargar la biblioteca de jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Cargar el archivo de JavaScript -->
  <script src="{% static 'js/rating.js' %}"></script>
  <script src="{% static 'js/confirmar.js' %}"></script>
{% endblock %}